#!/usr/bin/env python3
"""
Embed the generated demo artwork into a C++ translation unit, so the demo source
carries its own images with no filesystem or network dependency. The demo parser
emits `demo://<key>` URLs (e.g. demo://covers/fox-lantern.png); the generated
lookup maps a key to its bytes.

Run AFTER gen_demo_assets.py:
    python3 tools/embed_demo_assets.py
Writes: src/parsers/demo/DemoAssets.generated.cpp
"""
from __future__ import annotations
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, "..", "src", "parsers", "demo", "assets")
OUT = os.path.join(HERE, "..", "src", "parsers", "demo", "DemoAssets.generated.cpp")


def collect():
    items = []
    for root, _dirs, files in os.walk(ASSETS):
        for f in sorted(files):
            if not f.lower().endswith(".png"):
                continue
            path = os.path.join(root, f)
            key = os.path.relpath(path, ASSETS).replace(os.sep, "/")
            with open(path, "rb") as fh:
                items.append((key, fh.read()))
    return sorted(items)


def main():
    items = collect()
    lines = [
        "// GENERATED by tools/embed_demo_assets.py — do not edit by hand.",
        "// Original demo artwork, embedded so the demo source needs no network.",
        "#include \"aniparse/parsers/demo/DemoAssets.hpp\"",
        "",
        "#include <array>",
        "#include <string_view>",
        "",
        "namespace aniparse::parsers::demo {",
        "namespace {",
        "",
    ]
    total = 0
    for i, (key, data) in enumerate(items):
        total += len(data)
        body = ",".join(str(b) for b in data)
        lines.append(f"// {key} ({len(data)} bytes)")
        lines.append(f"constexpr unsigned char kAsset{i}[] = {{{body}}};")
        lines.append("")

    lines.append("struct Entry { std::string_view key; const unsigned char* data; std::size_t size; };")
    lines.append("")
    lines.append(f"constexpr std::array<Entry, {len(items)}> kAssets = {{{{")
    for i, (key, data) in enumerate(items):
        lines.append(f'    Entry{{ "{key}", kAsset{i}, {len(data)} }},')
    lines.append("}};")
    lines.append("")
    lines.append("} // namespace")
    lines.append("")
    lines.append("std::optional<std::span<const unsigned char>> asset_bytes(std::string_view key) {")
    lines.append("    for (const auto& e : kAssets) {")
    lines.append("        if (e.key == key) {")
    lines.append("            return std::span<const unsigned char>(e.data, e.size);")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return std::nullopt;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace aniparse::parsers::demo")
    lines.append("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"embedded {len(items)} assets, {total} bytes -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
